# Generated by Django 4.2.6 on 2023-10-20 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role_priv', models.CharField(default='employee', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='logic.departments')),
                ('org', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.organizations')),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.organizations'),
        ),
    ]
