# Generated by Django 4.2.6 on 2023-10-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
