# Generated by Django 4.2.6 on 2023-10-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True},
        ),
    ]
