# Generated by Django 4.2.6 on 2023-10-20 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
