# Generated by Django 4.2.6 on 2023-10-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_delete_orgadmins'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAdmins',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logic.organizations')),
            ],
            options={
                'db_table': 'org_admins',
            },
        ),
    ]
