# Generated by Django 4.2.6 on 2023-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_userinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default=''),
        ),
    ]
