# Generated by Django 4.2.6 on 2023-10-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_orgadmins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgAdmins',
        ),
    ]
