# Generated by Django 4.2.6 on 2023-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_userinfo_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='postal_code',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
