# Generated by Django 4.2.6 on 2023-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_userinfo_city_userinfo_country_userinfo_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', null=True),
        ),
    ]
