# Generated by Django 4.2.6 on 2023-10-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_delete_orgadmins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'managed': True},
        ),
    ]
