# Generated by Django 4.2.6 on 2023-11-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_userinfo_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_pic',
            field=models.URLField(default=None, null=True),
        ),
    ]
