# Generated by Django 4.2.6 on 2024-01-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logic", "0009_userinfo_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
