# Generated by Django 4.2.6 on 2023-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_alter_departments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
