# Generated by Django 4.2.6 on 2023-10-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_alter_departments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.organizations'),
        ),
    ]
