# Generated by Django 4.2.6 on 2023-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_alter_departments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='org',
            field=models.UUIDField(default=None),
        ),
    ]
