# Generated by Django 4.2.6 on 2023-10-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_alter_departments_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='org',
        ),
    ]
