# Generated by Django 4.2.6 on 2023-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0014_remove_departments_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='org',
            field=models.UUIDField(default=None),
        ),
    ]
