# Generated by Django 4.2.6 on 2023-10-21 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logic', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logic.departments')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.organizations')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.userinfo')),
            ],
            options={
                'db_table': 'user_files',
            },
        ),
    ]
