# Generated by Django 4.2.6 on 2023-10-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFiles',
        ),
    ]
