# Generated by Django 4.2.6 on 2023-11-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccheck',
            name='geo_enabled',
        ),
    ]
