# Generated by Django 4.2.6 on 2023-10-23 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_role'),
        ('fileoperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expiration_time', models.BigIntegerField()),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_url', models.URLField(default='')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileoperations.objects')),
                ('shared_with', models.ManyToManyField(related_name='shared_files', to='logic.userinfo')),
            ],
            options={
                'db_table': 'shared_files',
                'managed': True,
            },
        ),
    ]
