# Generated by Django 4.2.6 on 2023-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileoperations', '0002_delete_userfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('owner', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('avif_autodetection', models.BooleanField(blank=True, null=True)),
                ('file_size_limit', models.BigIntegerField(blank=True, null=True)),
                ('allowed_mime_types', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buckets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('path_tokens', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objects',
                'managed': False,
            },
        ),
    ]
