# Generated by Django 4.2.6 on 2023-10-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0002_sharedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfiles',
            name='expiration_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
