# Generated by Django 4.2.6 on 2023-11-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0003_seccheck_geo_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccheck',
            name='geo_enabled',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileoperations.allowedlocations'),
        ),
    ]
