# Generated by Django 4.2.6 on 2023-10-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buckets',
            table='storage"."buckets',
        ),
        migrations.AlterModelTable(
            name='objects',
            table='storage"."objects',
        ),
    ]
