# Generated by Django 4.2.6 on 2023-10-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0003_alter_sharedfiles_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfiles',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fileoperations.objects'),
        ),
    ]
