# Generated by Django 4.2.6 on 2023-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0004_alter_sharedfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfiles',
            name='download_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
