# Generated by Django 4.2.6 on 2023-11-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0005_accesslog_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
