# Generated by Django 4.2.6 on 2023-10-28 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fileoperations', '0005_sharedfiles_download_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.UUIDField()),
                ('file', models.UUIDField()),
                ('event', models.CharField(default='')),
            ],
        ),
    ]
