# Generated by Django 4.2.6 on 2023-11-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0012_alter_accesslog_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedfiles",
            name="state",
            field=models.CharField(default="active"),
        ),
    ]
