# Generated by Django 4.2.6 on 2023-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0013_sharedfiles_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedlocations",
            name="address_info",
            field=models.JSONField(default={}),
        ),
    ]
