# Generated by Django 4.2.6 on 2023-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0014_allowedlocations_address_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowedlocations",
            name="address_info",
            field=models.JSONField(default=dict),
        ),
    ]
