# Generated by Django 4.2.6 on 2024-01-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0015_alter_allowedlocations_address_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="user_profile",
            field=models.URLField(default=""),
        ),
    ]
