# Generated by Django 4.2.6 on 2024-01-02 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0016_accesslog_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesslog",
            name="user_profile",
        ),
    ]
