# Generated by Django 4.2.6 on 2024-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0017_remove_accesslog_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="profile_pic",
            field=models.URLField(default=""),
        ),
    ]
