# Generated by Django 4.2.6 on 2024-01-26 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0025_file_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File_Info",
        ),
    ]
