# Generated by Django 4.2.6 on 2024-01-26 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0026_delete_file_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="File_Info",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fileoperations.objects",
                    ),
                ),
            ],
            options={
                "db_table": "file_info",
            },
        ),
    ]
