# Generated by Django 4.2.6 on 2024-01-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0029_alter_sharedfiles_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="profile_pic",
            field=models.CharField(default=""),
        ),
    ]
