# Generated by Django 4.2.6 on 2024-01-29 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0030_file_info"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File_Info",
        ),
    ]
