# Generated by Django 4.2.6 on 2024-01-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fileoperations", "0034_file_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file_info",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_info",
                to="fileoperations.objects",
            ),
        ),
    ]
