# Generated by Django 4.2.6 on 2023-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_users_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='org_id',
        ),
    ]
