# Generated by Django 4.2.6 on 2023-10-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('logic', '0010_userinfo_dept_userinfo_org'),
        ('authenticate', '0003_remove_users_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.organizations'),
        ),
    ]
