# Generated by Django 4.2.6 on 2023-10-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('logic', '0010_userinfo_dept_userinfo_org'),
        ('authenticate', '0004_users_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='org',
            field=models.ForeignKey(null=True,default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.organizations'),
        ),
    ]
