# Generated by Django 4.2.6 on 2023-10-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_users_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='org',
        ),
    ]
