# Generated by Django 4.2.6 on 2023-10-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='users',
            name='org',
        ),
    ]
